# Naive Bayes

Naive Bayes methods are a set of supervised learning algorithms based on applying Bayes' theorem with the "naive" assumption of conditional independence between every pair of features given the value of the class variable. Bayes'theorem states the following relationship, given class variable $y$ and dependent feature vector $x_1$ through $x_n$,:

$$P(y \mid x_1, \dots, x_n) = \frac{P(y) P(x_1, \dots x_n \mid y)}
                                 {P(x_1, \dots, x_n)}$$

Using the naive conditional independence assumption, we have

$$\begin{align}\begin{aligned}P(y \mid x_1, \dots, x_n) \propto P(y) \prod_{i=1}^{n} P(x_i \mid y)\\\Downarrow\\\hat{y} = \arg\max_y P(y) \prod_{i=1}^{n} P(x_i \mid y),\end{aligned}\end{align}$$

Then, we can use Maximum A Posteriori (MAP) estimation to estimate $P(y)$ and $P(x_i \mid y)$; the former is then the relative frequency of class $y$ in the training set.

*References*:
H. Zhang (2004). The optimality of Naive Bayes. Proc. FLAIRS.

# 1 Gaussian Naive Bayes

GaussianNB implements the Gaussian Naive Bayes algorithm for classification.   
The likelihood of the features is assumed to be Gaussian:

$$P(x_i \mid y) = \frac{1}{\sqrt{2\pi\sigma^2_y}} \exp\left(-\frac{(x_i - \mu_y)^2}{2\sigma^2_y}\right)$$

The parameters $\sigma_y$ and $\mu_y$  are estimated using maximum likelihood.

**Example** - The training data is generated as follows:

In [1]:
import numpy as np
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
Y = np.array([1, 1, 1, 2, 2, 2])

**Q1**: Training a GaussianNB model:

In [2]:
from sklearn.naive_bayes import GaussianNB
gnb= GaussianNB()
gnb.fit(X,Y)

GaussianNB()

**Q2**: Predict the label of a data [-0.8,-1]:

In [3]:
X_test =np.array([[-0.8,-1]])
gnb.predict(X_test)

array([1])

In [4]:
X_test =np.array([[-2,-7]])
gnb.predict(X_test)

array([1])

# 2 MultinomialNB

The multinomial Naive Bayes classifier is suitable for classification with discrete features (e.g., word counts for text classification). 

*References*   
C.D. Manning, P. Raghavan and H. Schuetze (2008). Introduction to Information Retrieval. Cambridge University Press, pp. 234-265. http://nlp.stanford.edu/IR-book/html/htmledition/naive-bayes-text-classification-1.html

**Example** - The training data is generated as follows:

In [5]:
import numpy as np
X = np.random.randint(5, size=(6, 100))
y = np.array([1, 2, 3, 4, 5, 6])

In [6]:
X

array([[0, 4, 0, 2, 1, 4, 2, 4, 4, 1, 1, 0, 1, 0, 4, 3, 2, 0, 4, 1, 4, 3,
        0, 2, 1, 2, 3, 1, 4, 4, 2, 4, 4, 4, 3, 0, 0, 3, 0, 4, 1, 2, 1, 3,
        2, 4, 4, 3, 4, 3, 1, 3, 2, 1, 3, 1, 0, 0, 3, 2, 3, 2, 2, 4, 1, 0,
        0, 2, 2, 1, 2, 1, 3, 2, 3, 4, 1, 3, 3, 4, 1, 3, 2, 4, 1, 0, 2, 1,
        1, 1, 2, 4, 3, 2, 1, 1, 3, 3, 0, 3],
       [2, 3, 1, 0, 0, 1, 4, 4, 3, 2, 1, 3, 1, 3, 3, 1, 1, 0, 0, 2, 2, 2,
        4, 3, 4, 0, 2, 0, 0, 2, 3, 2, 3, 0, 0, 0, 3, 2, 4, 3, 4, 2, 3, 1,
        0, 3, 0, 4, 1, 3, 3, 0, 2, 3, 0, 4, 2, 1, 1, 0, 3, 0, 0, 4, 0, 4,
        0, 2, 4, 4, 3, 4, 1, 1, 0, 2, 3, 2, 3, 1, 4, 4, 0, 4, 0, 0, 4, 0,
        0, 0, 3, 1, 2, 0, 0, 4, 1, 4, 0, 3],
       [4, 2, 4, 1, 2, 2, 0, 0, 1, 1, 2, 0, 4, 4, 0, 3, 3, 3, 0, 0, 4, 4,
        1, 1, 0, 2, 1, 4, 3, 0, 3, 4, 0, 0, 1, 4, 4, 2, 0, 1, 3, 4, 3, 3,
        4, 4, 2, 0, 1, 2, 0, 0, 0, 1, 3, 0, 4, 4, 3, 4, 0, 2, 1, 4, 1, 4,
        4, 0, 0, 3, 2, 3, 1, 2, 1, 3, 4, 3, 0, 0, 4, 4, 1, 3, 4, 4, 4, 2,
        1, 3, 0, 2, 2,

**Q3**: Training a MultinomialNB model:

In [7]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(X,y)

MultinomialNB()

**Q4**: Predict the label of a data X[2:3]:

In [8]:
mnb.predict(X[2:3])

array([3])

# 3 Process on 'Iris' Data

We have studied how to use KNN algorithm to do classification task on 'iris' data. Here,we are going to employ the GaussianNB to conduct the same task. 

In [9]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
iris_dataset = load_iris()
X_train, X_test, y_train, y_test = train_test_split(
iris_dataset['data'], iris_dataset['target'], random_state=0)

**Q5**：Report the acuracy result on test data:

In [10]:
from sklearn.metrics import accuracy_score ,classification_report,confusion_matrix

In [15]:
gnb= GaussianNB()
gnb.fit(X_train,y_train)

GaussianNB()

In [16]:
y_test_pred= gnb.predict(X_test)
print("Accuracy ",accuracy_score(y_test,y_test_pred))

Accuracy  1.0


In [17]:
mnb = MultinomialNB()
mnb.fit(X_train,y_train)

MultinomialNB()

In [18]:
y_test_pred= mnb.predict(X_test)
print("Accuracy ",accuracy_score(y_test,y_test_pred))

Accuracy  0.5789473684210527
